version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: phishing-backend
    volumes:
      - ./backend:/workspace
    working_dir: /workspace
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
